project/config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

project/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

project/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end
end

project/app/helpers/application_helper.rb
module ApplicationHelper
end

project/app/helpers/pages_helper.rb
module PagesHelper
end

project/app/views/layouts/application.html.erb
<!-- Inspiration: https://store.epicgames.com/en-US/ -->
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <nav class="text-white bg-black navbar sticky-top bg-body-tertiary d-flex justify-content-center">
    <a class="navbar-brand"><img src="https://img.icons8.com/?size=1x&id=yGcWL8copNNQ&format=png" alt="Bootstrap" width="40" height="40"></a>
    
    <ul class="nav d-flex justify-content-center">
      <li class="nav-item">
        <%= link_to "Home", pages_home_path, :class => 'nav-link fw-bold text-light' %>
      </li>
      <li class="nav-item">
        <%= link_to "Contact", pages_contact_path, :class => 'nav-link fw-bold text-light' %>
      </li>
    </ul>
  </nav>
  
  <%= yield %>

  </body>
</html>

project/app/views/pages/contact.html.erb
<form class="m-5">
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1">
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

project/app/views/pages/home.html.erb
<div class="container-fluid p-0">
  <div class="position-relative text-center">
    <img class="img-fluid" src="https://dummyimage.com/1920x1080/787678/fff&text=+">
    <div class="position-absolute top-50 start-50 translate-middle">
      <h1 class="text-white fw-bold text-center">Ashtons Epic Website</h1>
      <p class="text-white text-center fs-3">very very epic</p>
      <%= link_to "Contact Us Now", pages_contact_path, :class => 'text-decoration-none fw-bold text-light rounded-pill fs-4 bg-danger px-5 py-2 d-block' %>
    </div>
  </div>

  <h2 class="text-center fw-bold mt-4 fs-1">Explore More Content</h2>

  <div class="d-flex justify-content-between p-2">
    <% for i in 0..5 do %>
      <div class="p-1">
        <img class="img-fluid" src="https://dummyimage.com/300x400/000/fff">
        <h3>Name</h3>
      </div>
    <% end %>
  </div>

  <div>
    
  </div>

</div>